from dataclasses import dataclass

@dataclass
class PregameStats:
    id: int
    homeTeamName: str
    awayTeamName: str
    seasonStartYear: int
    gameDate: str
    homeWinRatio: float
    homeRecentWinRatio: float
    homeRecentGoalsAvg: float
    homeRecentConcededGoalsAvg: float
    homeRecentSogAvg: float
    homeRecentPpgAvg: float
    homeRecentHitsAvg: float
    homeRecentPimAvg: float
    homeRecentBlockedShotsAvg: float
    homeRecentTakeawaysAvg: float
    homeRecentGiveawaysAvg: float
    homeGoalsAvg: float
    homeGoalsAvgAtHome: float
    homeRecentGoalsAvgAtHome: float
    homeConcededGoalsAvg: float
    homeConcededGoalsAvgAtHome: float
    homeRecentConcededGoalsAvgAtHome: float
    awayWinRatio: float
    awayRecentWinRatio: float
    awayRecentGoalsAvg: float
    awayRecentConcededGoalsAvg: float
    awayRecentSogAvg: float
    awayRecentPpgAvg: float
    awayRecentHitsAvg: float
    awayRecentPimAvg: float
    awayRecentBlockedShotsAvg: float
    awayRecentTakeawaysAvg: float
    awayRecentGiveawaysAvg: float
    awayGoalsAvg: float
    awayGoalsAvgAtAway: float
    awayRecentGoalsAvgAtAway: float
    awayConcededGoalsAvg: float
    awayConcededGoalsAvgAtAway: float
    awayRecentConcededGoalsAvgAtAway: float
    winner: float
    isExcluded: bool
